services:
  homepage:
    image: ${HOMEPAGE_IMAGE}
    container_name: homepage

    restart: unless-stopped

    ports:
      - "3000:3000"

    environment:
      TZ: ${TZ}
      HOMEPAGE_ALLOWED_HOSTS: ${HOMEPAGE_ALLOWED_HOSTS}

    volumes:
      - ./configs/homepage:/app/config
      - ./configs/homepage/images:/app/public/images
      - /var/run/docker.sock:/var/run/docker.sock:ro

    networks:
      - homelab

networks:
  homelab:
    name: homelab
