- Infrastructure:
    - Homepage:
        href: http://192.168.29.230:3000
        icon: homepage.png
        description: Homelab Dashboard
    - File Browser:
        href: http://192.168.29.230:8080
        icon: filebrowser.png
        description: File Management
- Monitoring:
    - Uptime Kuma:
        href: http://192.168.29.230:3001
        icon: uptime-kuma.png
        description: Service Monitoring
