- Infrastructure:
    - Homepage:
        href: http://home.home.arpa
        icon: homepage.png
        description: Homelab Dashboard

    - File Browser:
        href: http://files.home.arpa
        icon: filebrowser.png
        description: File Management

- Monitoring:
    - Uptime Kuma:
        href: http://status.home.arpa
        icon: uptime-kuma.png
        description: Service Monitoring
